apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  # Enable ApplicationSet controller for auto-discovery
  applicationSet: {}
  server:
    # Hostname for ingress resource
    host: argocd.pane.run
    # Disable OpenShift routes
    route:
      enabled: false
    # Use ClusterIP service type (ingress will handle external access)
    service:
      type: ClusterIP
    # Enable ingress for external access
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        # Enable cert-manager to issue TLS certificate
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # Force HTTPS redirect
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
      tls:
        - secretName: argocd-server-tls
          hosts:
            - argocd.pane.run
    # Disable internal TLS (ingress handles TLS)
    insecure: true
